// Code generated by girgen. DO NOT EDIT.

package gnomedesktop

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: gnome-desktop-4
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
import "C"
