// Code generated by girgen. DO NOT EDIT.

package gnomebg

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: gnome-bg-4 gnome-desktop-4
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
import "C"
